### ISSUE TITLE
Nivo bars text overlap on smaller charts

### ISSUE THREAD

**Issue by GarvinH** [TBS-EACPD/infobase#1019]
related #1013

Found that smaller charts in general have quite a fair bit of styling annoyances.
Minor (?) stuff mostly, maybe we won't bother fixing it(?)...

detailed spending - sobjs main offender I've taken notice to

![image](https://user-images.githubusercontent.com/25855114/114898639-4d4c1900-9de0-11eb-8112-a40dc9785161.png)
- [x] x-axis labels are poorly scaled/overlapping

![image](https://user-images.githubusercontent.com/25855114/114898828-779dd680-9de0-11eb-8667-7b5dc54ad55c.png)
- [ ] Labels on the right aren't centered with the bars

![image](https://user-images.githubusercontent.com/25855114/114898994-9bf9b300-9de0-11eb-81f4-1d2bb9d9f43e.png)
- [ ] y-axis labels overlapping

**Comment by Stephen-ONeil** [comment]
Yeah, ouch. Worth doing something about. 
  - Maybe give horizontal bars more height row height by default and set `overflow: hidden` on the labels (if possible, hope that's not text inside an svg or something)
  - Label overlaps on the x-axis are easier to resolve with rotated labels, might just be a case of looking around for cases that may require switching to those

**Comment by GarvinH** [comment]
related #1025 - x-axis was rotated to stop the overlap
