### ISSUE TITLE
Storybooking components

### ISSUE THREAD

**Issue by GarvinH** [TBS-EACPD/infobase#1021]
## client/src/components

- [x] Accordion
- [x] BackToTop
- [x] CheckBox
- [x] DisplayTable
- [x] HeightClipper
- [x] IconGrid 
- [x] FixedPopover
- [x] FocusLockedModal
- [x] ModalButton
- [x] StatelessModal
- Typeahead
  - [x] Basic Typeahead
  - [x] Typeahead with headers + options
- [x] Alert banner
- [x] Card background image
- [x] Card centerer image
- [x] Card left image
- [x] Card list
- [x] Card top image
- [x] Countdown
- [x] Countdown circle
- [x] Debounced Text input
- [x] Details
- [x] Dropdown menu
- [x] Fancy UL
- [x] Filter table
- [x] Footnote list
- [x] Header notification
- [x] Key concepts
- [x] labelled box
- [x] labelled table
- [x] panel
- [x] radio button
- [x] select
- [x] share button
- [x] sort direction
- [x] spinner wrapper (Different formats/sizes)
- [x] tabbed content
- [x] tab loading wrapper
- Tombstones
  - [x] Unlabelled tombstone
  - [x] Labelled tombstone
- [x] Two Level Select
- [x] Write to clipboard

Edit: This is just a general guideline. Feel free to have multiple stories for each component to show how different props can change the interface/functionality!

**Comment by ktw1016** [comment]
👍😃
