### ISSUE TITLE
Have a CI step that checks that webpack output is clean

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#1068]
We should have a check that the webpack output has no errors or warnings. This is going to ensure that static typing and linting both pass. It's also going to speed up PR reviews.

This should not hold back dev-link creation or other CI steps

**Comment by Stephen-ONeil** [comment]
Linting portion is covered by a distinct lint job in #1350, maybe type checking could be handled similarly. Maybe speed up CI builds by disabling lint and type checking after that (if it's worth while, might be relatively minor since linting during builds at least s cached).
