### ISSUE TITLE
bug with Details on Statutory Items in Estimates and Details on Voted Items in Estimates 

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#1070]
http://dev.ea-ad.ca/master/index-eng.html#orgs/gov/gov/infograph/financial/.-.-(panel_key.-.-'in_year_stat_breakdown)

![Screen Shot 2021-05-07 at 11 20 55 AM](https://user-images.githubusercontent.com/7769215/117471875-4c615f80-af26-11eb-87df-7cbab04d7b26.png)

**Comment by Stephen-ONeil** [comment]
Load the finance infographic, switch to another infographic (e.g. people), then switch back to finances. Do that a couple times, it starts appending additional copies of the dept name on each re-load of the panel. Must be some junk in there mutating the underlying data, ugh.
