### ISSUE TITLE
User feedback: RPB column toggle behaviour

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#1151]
When using the `DisplayTable` "Select columns" feature to toggle off an index column, the rows are not re-grouped by the remaining columns. For example, the [FTE by program table](http://dev.ea-ad.ca/master/index-eng.html#rpb/.-.-(subject.-.-'gov_gov.-.-columns.-.-false)) does _not_ become an FTE by org table just by [toggling off the program](http://dev.ea-ad.ca/master/index-eng.html#rpb/.-.-(table.-.-'programFtes.-.-subject.-.-'gov_gov.-.-columns.-.-(.-.-'*7b*7bpa_last_year_5*7d*7d.-.-'*7b*7bpa_last_year_4*7d*7d.-.-'*7b*7bpa_last_year_3*7d*7d.-.-'*7b*7bpa_last_year_2*7d*7d.-.-'*7b*7bpa_last_year*7d*7d.-.-'*7b*7bplanning_year_1*7d*7d.-.-'*7b*7bplanning_year_2*7d*7d.-.-'*7b*7bplanning_year_3*7d*7d))) column.

Regrouping wasn't ever the intended behaviour of the "Select columns" menu. At least one user assumed it would be though, and it does sound like a useful feature to have ... I don't think it's feasible to add to the default "Select columns" though, can't regroup arbitrary table column contents (some columns will be explicitly non-summable). Might just be a special, separate, control for tables (with only summable columns) to opt in to?

Lots of open questions here, please share your thoughts. I didn't refresh my self on the `DisplayTable` API/features before opening this, and I think there's a lot of open room to design any number of "solutions" to this.

**Comment by csong202** [comment]
I think this feature would only make sense for tables with a "Program" column. It wouldn't really make sense on Employee Type or Geographic Region

**Comment by Stephen-ONeil** [comment]
Hm, it might! Using the employee tables for instance, rolling up other rows when the dimension is disabled would give a table of per-dept employee totals while disabling the dept column who give government totals broken down by the remaining dimension (e.g. Employee Type).

Can't say it would always make sense for every dataset though, and the value of the feature would vary a lot. For example, all people tables sum to the same total if you remove the dimension, so lots of redundancy there. So it might not be a good default behaviour for all tables, even just within the RPB. I think the question is whether it's worth the effort/added ongoing complexity for the sake of the cases where it seems to make sense.
