### ISSUE TITLE
See if the local dev server(s) can be tweaked to set no-cache on all resources

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#1157]
Should always have browser dev tools open with caching disabled when working with local builds, but there's always the occasion that you close your dev tools or open a local link in a new tab and forget. Disabling caching from the local server(s, maybe both the client http server and the GraphQL API server) would save some headaches and debug time when that happens, haha.

**Comment by sranc046** [comment]
Not the best solution but maybe this could help: https://chrome.google.com/webstore/detail/classic-cache-killer/kkmknnnjliniefekpicbaaobdnjjikfp?hl=en. Basically a chrome extension that you can toggle on/off to load pages without cache. Seen a few comments around StackOverflow and such that recommend it.

**Comment by Stephen-ONeil** [comment]
Maybe individual devs could use something like that if they want. Some chance that would be a tricky gotcha some day as a source of different behaviour across browsers/in CI/between devs.
