### ISSUE TITLE
Write an EnsureLoaded React component using react-async

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#117]
At first blush, although I haven't thought too deeply about implementation, I think this [react-async](https://github.com/ghengeveld/react-async) library could be easily leveraged in to a reusable `EnsureLoaded` component, cleaning up and centralizing the scattered asynchronously state updating `ensure_loaded` calls in so many of our subapps.

Could potentially clean out some, potential, memory leaks we've had kicking around from the old `ensure_loaded` pattern's awkward interaction with React, depending how this react-async library behaves under the hood.

**Comment by ktw1016** [comment]
this would be great

**Comment by GarvinH** [comment]
Made a small attempt at this.

Unfortunately, doing this isn't as easy as removing the loading value from state. There's a lot more stuff that the ensure_loaded methods are currently intertwined with. Undoing these may take a bit of time to achieve.

**Comment by Stephen-ONeil** [comment]
#1004 is related, a wrapper around some apollo hooks might mostly address what we'd want from this.
