### ISSUE TITLE
Add glossary side menu

### ISSUE THREAD

**Issue by sranc046** [TBS-EACPD/infobase#1253]
Example from USASpending: https://www.usaspending.gov/disaster/covid-19/?publicLaw=all. Clicking on glossary term will bring up the side menu.

The menu will allow users to browse the whole content of the glossary without losing their place on the InfoBase.

**Comment by Stephen-ONeil** [comment]
With the right focus management, this would also address #1016 (although #1230 might beat this idea to the punch).
