### ISSUE TITLE
Move on-page focus when selecting link in Table of Contents

### ISSUE THREAD

**Issue by pcraig3** [TBS-EACPD/infobase#1317]
Hello!

Great site, looks generally super cool.

Just noticed a minor issue with your "table of contents". When I am using <kbd>Tab</kbd> to move around the page, I can open the Table of contents, select a subheading and then press <kbd>Enter</kbd> to actually move the window down, but if I keep using <kbd>Tab</kbd>, then it whips me back up to the next item in the table of contents.

Clicking/activating a table of contents link will visually move focus, but the real browser focus stays inside of the Table of Contents.

I have a little gif of this, although you can't really see when I press  <kbd>Tab</kbd>, so you have to imagine it happening.

---

![Screen Recording 2021-12-03 at 13 33 18](https://user-images.githubusercontent.com/2454380/144655325-e4e728b3-d060-46fc-a256-9037ece3e0de.gif)

**Comment by Stephen-ONeil** [comment]
Good catch, thanks!
