### ISSUE TITLE
Prefer min-width media queries over max-width

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#139]
After PR #6 gets merged, we'll finally have consistent breakpoints, including all of our grid systems being consistent on using min-width queries. Temporary trade off, anything using a max-width media query will transition styling 1px before the grid system/most other content. This only hits at three pixel-specific screen sizes, but it's there and sometimes fairly noticeable.

Solution is to, as much as possible, stick to min-width queries. This should be added to the project style guidelines, and we should make some effort to standardize the existing queries (there's a lot and it's not always trivial to invert them though).

**Comment by Stephen-ONeil** [comment]
Not dead, but should be documented in wiki then closed.

**Comment by ktw1016** [comment]
Also related to #639

**Comment by GarvinH** [comment]
Some files still have max-width lying around. I'm gonna clean it up.

**Comment by GarvinH** [comment]
There's a couple max-width lying around so I'll try to clean it up

**Comment by GarvinH** [comment]
Now that the .98px max is being used, there isn't any problem with the 1px gap anymore. 

I've also updated the wiki point so that is just says preferably use min-widths instead.

If this is all good, I'll close this issue
