### ISSUE TITLE
Internal users can't find the planned spending variance information

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#149]
Report a problem got an issue where a user was having trouble finding the notes attached to >10% variation in FTEs or spending. Those are displayed in footnotes on the financial infographics (next to the data they refer to), but it's hard to know how to help users like this, who are (probably) looking for last year's or other departments' notes to write this years. Maybe some combination of an FAQ on the InfoBase side and/or documentation for Titan explaining where things are going to go on InfoBase and how they will be displayed would be helpful.

**Comment by Stephen-ONeil** [comment]
Presumably, this isn't an InfoBase problem. They're "hard to find" because they're scattered about to be near the data they are relevant to. Only an internal user looking for previous year's data to help prepare the next year's would think this is wrong.
