### ISSUE TITLE
Look at the introductory text for govt-level results infographic

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#175]
(for DP and DRR panels). Right now it's a list of definitions and overall stats. Can we do better? Is there text from TBS's DP/DRRs page that we can crib?

Also add the links to the DP and DRR reports since we deleted those from the about panels. Could be an anchor link to the first letter of the dept name, save users a click

**Comment by Stephen-ONeil** [comment]
Was this addressed by #358?

**Comment by Stephen-ONeil** [comment]
Pretty sure this was fixed by #358
