### ISSUE TITLE
Rethink gocographic

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#234]
There might be a better way to display this data.

Two main features:

- There's both spending and FTEs, and it's interesting to compare the distributions (FTEs for crowns would help a lot)
- Two levels of categorization

Some unusual examples [here](https://medium.com/s/story/five-unusual-alternatives-to-pie-charts-389cc4676974)

Some of the weirder ones would be pretty interesting, especially since we have longitudinal data. But they're complicated enough that they might want to be a labs feature.

Maybe something like this, with two different dumbell charts (one for spending, one for FTEs)

![Screen Shot 2019-10-03 at 10 43 07 AM](https://user-images.githubusercontent.com/10406459/66137179-b5565800-e5ca-11e9-9678-a30d7f30c6b0.png)

**Comment by Stephen-ONeil** [comment]
I think it needs some rethinking, but I'd prefer something more standard. It's one obscure panel only available at the government level, don't want it to be something that requires much maintenance.
