### ISSUE TITLE
Multiple orgs changed names

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#256]
4 orgs (SIRC, OCSEC, NEB, and CEAA) apparently changed names this year, but their old names remain in the FAA schedule.

Not sure why we can't go ahead and change their applied names though. Looks like they've all changed their websites.

**Comment by Stephen-ONeil** [comment]
@cookkate has this resolved itself?

**Comment by cookkate** [comment]
I think so, yeah!
