### ISSUE TITLE
DisplayTable should be filterable

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#261]
Columns are optionally sortable but there's no functionality for filtering by any means (selecting an option or free-text entry).

**Comment by ktw1016** [comment]
do you mean like filtering by a column containing specific text?

**Comment by ktw1016** [comment]
@cookkate

**Comment by cookkate** [comment]
Either (probably) that, or filterable from a drop down list in the case that there's only a limited number of possibilities.
