### ISSUE TITLE
Feedback campaign

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#265]
Proposal: some time during a high-traffic period (DRRs would be optimal, if we want to wait that long...DPs are a runner up but will probably attract less outside-the-govt traffic), do a limited-time "feedback" campaign asking people (via popup?) to "like" their favourite panels or/and submit feedback via the Report a Problem widget / feedback form.

**Comment by Stephen-ONeil** [comment]
Closed by #476
