### ISSUE TITLE
Indicator text diff running pretty slow

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#290]
Reloads (ie when you click something on the filter by status thing) take ~5s on IB_q. Mysterious as to why, it's not reloading data or re-running diff.

**Comment by Stephen-ONeil** [comment]
Important to note, performs much better on builds produced by prod or dev builds, only slow on the quick builds. Main difference between dev and quick builds is whether babel runs, indicating this might be a case where babel is (unintentionally?) optimizing something while transpiling.

**Comment by ktw1016** [comment]
Agreed with dead, it works fine on my Mac
