### ISSUE TITLE
Indicator diff filter doesn't work as expected

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#293]
Right now it understands "target changed" to be a subset of "indicator/methodology changed", but that's not how it appears to the user.

Need to fix the indicator processing so that it measures those two things separately.

**Comment by ktw1016** [comment]
Just a reminder note for myself: logic of status message for `one or more words changed` also need to be fixed. Also, the wording should match to `Indicator/methodology changed`
