### ISSUE TITLE
RPB should provide an export button on summary reports

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#302]
Always a bit confusing that an export button is available for granular data but not summary data, especially since summary is the default (so users looking for a download might bounce without ever seeing the option).

**Comment by ktw1016** [comment]
So is this expected to produce exactly same csv as the one for granular data?

**Comment by Stephen-ONeil** [comment]
It would easy to do that, but I think the expectation would be for it to export something that looks the same as the data being presented below.
