### ISSUE TITLE
GOCO graph on-click broken in IE11

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#328]
Doesn't spawn the sub-graph.

Also, the nivo tooltip will persist on the last element hovered on even when you mouse off the graph entirely. Might be the same bug, if something's messing with events on it? Haven't looked in to it, might be unrelated/a nvio bug.

**Comment by ktw1016** [comment]
both hover and click doesn't work. I believe it's because Nivo is producing different DOM structure... I'll take a look when I get to work at home (I'm hoping I'll be able to test IE on my personal computer)

**Comment by Stephen-ONeil** [comment]
You could bring the work tablet home if you need a device with IE.

**Comment by ktw1016** [comment]
I have windows machine at home, hopefully that will work

**Comment by Stephen-ONeil** [comment]
If I remember right (I might be thinking of something else) you might need to edit your registry to get to IE11? Depending one how the system was installed. It's always there, but it's hidden by default for a lot of install versions.

Or maybe I'm thinking of something else like the old media player or classic photo viewer, dunno.
