### ISSUE TITLE
BaseTypeahead makes hacky use of react-bootstrap-typeahead

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#34]
react-bootstrap-typeahead seemed like the best choice initially, but, to get all the desired behaviour/fix performance issues in our typeahead, I had to tap in to the undocumented (i.e. subject to unannounced changes) internal API of the react-bootstrap-typeahead component. Clever me.

As expected, the internals were changed without warning between 3.2.4 and 3.3.1 (as is their prerogative), breaking things. I've pinned the version at 3.3.1 for now, but we're going to have to do this properly eventually.

Options:
  1. only use official react-bootstrap-typeahead API (and lose features + take a performance hit, unless they release an update improving it themselves)
  2. find another react typeahead component library that does what we want
  3. make our own typeahead from scratch
  4. ... keep hacking over top of react-bootstrap-typeahead, and just keep an eye out for bugs introduced by new versions

**Comment by Stephen-ONeil** [comment]
Haven't read through this in full yet, but I'm guessing it would help in getting a11y right on any re-implementation of a typeahead.
https://adamsilver.io/articles/building-an-accessible-autocomplete-control/

**Comment by GarvinH** [comment]
related #739
