### ISSUE TITLE
Use MongoDB search as primary infograph searching method

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#340]
I don't think this is a priority or anything, but I've got some recent thoughts on this. The main benefit to doing the search in the API instead of the client is that we can drastically reduce the initial lookup bundle size by not loading names/descriptions or other text heavy fields.

## potential problem: language specific search

One potential roadblock is, as mentioned in #165, that mongodb does not seem to support to text-searching a collection using 2 distinct text-indexes. 

We can support per-language search by duplicating the data. The english can search english columns and use the "main" collection, and we can have a duplicate collection for french data. Or, for a more symmetric solution, we can create separate "searchable" tables for each language. 

It sounds kind of annoying, especially if we add searching to more collections, but denormalization is extremely common in no-sql stores. We're lucky mongodb even support secondary indexes, other nosql stores force you to  [re-invent that wheel](https://docs.microsoft.com/en-us/azure/architecture/patterns/index-table)

I'm not sure if language is the main reason we haven't started using mongo-search in production. If it turns out people are fine searching both languages, this might just be a solution looking for a problem. 

## Potential problem: initial latency

Another concern is loading up the infobase and expecting the search to work immediately while waiting for a cold lambda to warm up.

I'm hoping this isn't a big deal, but I suppose we can fire off a dummy "wake up" query to the API when a search component gets mounted. Are we already doing anything like that, e.g. when the app gets loaded?

**Comment by Stephen-ONeil** [comment]
Further downsides to "searching both languages", the language set for the text index itself determines filtering of "stopwords" (the, an, etc) and the support for "stemming" (ability to match root words, e.g. matching a query for run against running). Can set language to "none" at the cost of automatic stopword removal and stemming support.

Stemming is more important, but even then it is weaker than our long standing approach of allowing searches to match arbitrary partials. This behaviour is unavailable with MongoDB text searching.

For now, the regex based approach taken in #1302 will be our standard. It suffers from the same initial latency concern, and may prove to be slower at scale, but it matches the partial matching behaviour and avoids the language concerns. Can be revisited once all searching is supported server side.
