### ISSUE TITLE
welcome mat bug

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#341]
Canadian Grain Commission's negative expenditures for 2014-2017 aren't showing up properly:

![Screen Shot 2019-11-07 at 4 22 39 PM](https://user-images.githubusercontent.com/10406459/68428876-008bf980-017b-11ea-9b8f-d242886a9af1.png)

**Comment by ktw1016** [comment]
uhhhhh so I'm thinking I should do the same as I did in isc panel and check for first & last active data point and include all data in between? Right now, it instead checks if each data point is greater than 0

**Comment by ktw1016** [comment]
How could they have spent negative amounts of money though?

**Comment by cookkate** [comment]
They have revenues (money coming in from fees and other programs)

This one is going to be a tricky one because we have to decide how we want to display revenue-only years on the welcome mat. We can't just filter it out.

**Comment by ktw1016** [comment]
okay

**Comment by Stephen-ONeil** [comment]
This might be this same thing, might not, [Canadian Pari-Mutuel Agency](http://dev.ea-ad.ca/master/index-eng.html#orgs/program/AGR-AAB00/infograph/financial/.-.-(panel_key.-.-'welcome_mat)):

![image](https://user-images.githubusercontent.com/11301919/71022730-305de380-20cf-11ea-9a74-40dbf9d0a544.png)

**Comment by Stephen-ONeil** [comment]
Fixed, at some point.
