### ISSUE TITLE
Tag panels with relevant glossary entries

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#345]
Thinking that it might be good to tag panels with relevant glossary entries, make it standard. There's lots of panels that might have relevant definitions that don't show up exactly in text and, as a result, don't get direct glossary tooltips/links. Maybe put them in a details drawer like the footnotes (or rename the existing one to Footnotes & Definitions), or add a little dictionary icon to the utils bar to bring up a definitions modal.

Right now, a couple panels include glossary entires with their footnotes, but not in a standard (or robust) way. Preferable (IMO) to having the same text in both the footnote and glossary datasets though, since they'd risk getting out of sync.

**Comment by cookkate** [comment]
I'd worry that we'd just end up with an explosion of footnotes. There's already a ton to read on pretty much every panel.

**Comment by Stephen-ONeil** [comment]
Ahh, true. Ok, if this happens it won't be as footnotes.
