### ISSUE TITLE
Multiple bugs in revenue-heavy (revenue-only?) program infographics

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#360]
e.g. https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/program/AGR-AAB00/infograph/financial

**Comment by ktw1016** [comment]
What are the multiple bugs in this?

**Comment by Stephen-ONeil** [comment]
Duplicate of #341 (? maybe, otherwise I don't know what it's about, may have been the state of this infographic under old data?)
