### ISSUE TITLE
Tables in panels should have a button to display raw (unformatted) data

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#37]
This should be doable?

**Comment by ktw1016** [comment]
This will be part of #585

**Comment by ktw1016** [comment]
This is actually pretty redundant to #561 since #561 will copy data unformatted. Plus, most of tables are already in raw values. Hence closing this issue, feel free to reopen if needed

**Comment by Stephen-ONeil** [comment]
Well, having it in-site would be nicer than having to open a spread sheet and paste out the raw values, but it's probably better if the chart tables just always display un-rounded values either way.

What we should do is sweep through and make sure that's the case. I know the pie chart tables actually have less accuracy on their percent formatter in the table than in the legend by default right now, for example. That should be reversed.
