### ISSUE TITLE
Post-DRR glossary cleanup

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#375]
In addition to the cleanup on the code side there are a couple of glossary definitions that are out of date, namely SSP (subprograms), and PAA (program architecture alignment)

**Comment by AlexCLeduc** [comment]
does infobase care about subsub and PAA anymore?

**Comment by Stephen-ONeil** [comment]
Nope. Pretty sure this issue is to delete the glossary entires we no longer care about though, so probably not dead (unless someone's done that?).

**Comment by Stephen-ONeil** [comment]
RE: dead?

> probably not dead (unless someone's done that?).

Still not done. We need to coordinate with the pipeline on this one.

**Comment by Stephen-ONeil** [comment]
Sort of related to #359. This should probably be a general glossary review rather than a specific task for removing definitions from the old results policy. Likely other out of date definitions in there.

**Comment by Stephen-ONeil** [comment]
Actually, I'll close this to merge with #359.
