### ISSUE TITLE
Deeper level to more refine infographs within a bubble

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#376]
For example, after selecting `Finances` bubble, have some sort of a filter (like show only transfer payments panels, or FTE panels, etc.)

![Screen Shot 2019-11-25 at 2 40 30 PM](https://user-images.githubusercontent.com/29746626/69572192-9dc79a00-0f91-11ea-9730-279d01b05e3f.png)
Suggestion from Infobase Heuristic Report

**Comment by ktw1016** [comment]
We know what tables for each panel so we can filter depending on what data each panel contains.
Problems with that:
1. Budget not tabled
2. Key concepts, empty table (this isn't actually a problem)

**Comment by ktw1016** [comment]
I think #529 should have closed it. Reopen if needed

**Comment by ktw1016** [comment]
This should never have closed actually

**Comment by Stephen-ONeil** [comment]
Duplicate of #642
