### ISSUE TITLE
hover tooltip improvements

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#377]
![Screen Shot 2019-11-25 at 2 42 50 PM](https://user-images.githubusercontent.com/29746626/69572320-e5e6bc80-0f91-11ea-9f55-6a8cac0d358a.png)
Seems like a valid point

**Comment by Stephen-ONeil** [comment]
1) is more about reviewing glossary content. Not going to put popups in popups.

2) is possibly valid some times, but is very case-by-case. Not something I want to force a full text review for, we just need to be applying our best judgement any time we write new/update old text.
