### ISSUE TITLE
rounded off edges

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#378]
![Screen Shot 2019-11-25 at 2 45 29 PM](https://user-images.githubusercontent.com/29746626/69572494-3d852800-0f92-11ea-93de-a7e8d582c4ad.png)

Not too sure how important it is, but it seems like bubbles are the only 90 degree edges

**Comment by Stephen-ONeil** [comment]
I like the idea of the only perfect squares in the UI, outside of graphs, are things we insist on calling "bubbles".

I'll play around with rounding them off a bit for consistency though.
