### ISSUE TITLE
Look in to react-table

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#384]
https://github.com/tannerlinsley/react-table

https://medium.com/@tannerlinsley/why-i-wrote-react-table-and-the-problems-it-has-solved-for-nozzle-others-445c4e93d4a8#.axza4ixba

I really like how it doesn't try and offer a UI and a billion configuration options, leaves that up to you and just handles all the under-the-hood mucking about. If we ever want to do an RPB refactor, I think this might be the best choice for driving the tables/datagrid in it.

**Comment by ktw1016** [comment]
This looks cool, what problems do we have that this table is solving?

**Comment by ktw1016** [comment]
I'd say close this

**Comment by Stephen-ONeil** [comment]
Well, we ended up building a lot of the functionality from this in the `DisplayTable` over time (still missing pivoting). I think it would have been better to use this from the start as a solid foundation, but I'll close this for now since so much effort's already been put in to our own tables. Consider this library again if `DisplayTable` ever starts to feel creaky.
