### ISSUE TITLE
Add content security policy meta tag to index html files

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#385]
Should be pretty straightforward to configure well. Not a huge benefit, since we bundle and serve everything we pull from npm ourselves. Would pretty much only protect against the subset of supply chain attacks that call out for their payload instead of injecting it (I imagine this is not the supply chain attack norm, as it would be highly visible and easily defeated by good CSP).

**Comment by GarvinH** [comment]
closing in favour of above
