### ISSUE TITLE
"See the data" --> "See the data in our report builder"

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#402]
Or something similar.

**Comment by ktw1016** [comment]
Don't we already kinda have this? It links to rpb link

**Comment by Stephen-ONeil** [comment]
I think this was about rewording the phrasing OF those links to the report builder

**Comment by ktw1016** [comment]
Was this for partition diagrams? I can't find where "see the data" is

**Comment by Stephen-ONeil** [comment]
Panel footers and partition diagram. I don't think "See the data in our report builder" is great for the panels though, they aren't always RPB links (at least, the budget panel doesn't link to the RPB). Maybe something like "See more" or "Additional data"?

**Comment by ktw1016** [comment]
TBH this all seems same, I don't like "See the data in our report builder" because it's too long.
I don't see what's difference between the current text and "See more", "Additional data". Please close the issue if you agree, or leave it open if you think this is necessary change

**Comment by Stephen-ONeil** [comment]
I can think of some reasons it's worth changing, but I don't actually remember what specifically prompted this issue. We can close it.
