### ISSUE TITLE
Fate of the CRSO estimates table

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#404]
Never got in to use outside of the report builder (where it is barely used). It will also be out of sync with estimates update (such as the imminent Supps A release) because it requires manual effort to compile (currently).

I'm for dropping it, lots of maintenance for little to no value. It will probably still go out on Open Data, but there it is less important that it stays in-sync with the other estimates documents.

**Comment by rossbm** [comment]
I'm in favour of removing it also. I don't think that the data is very useful. We would probably drop it from Open Data also. I think that Nicolas and Shane are also supportive.

**Comment by Stephen-ONeil** [comment]
Sounds settled to me then, I'll give it the permanent axe. Can you drop the csv from future pipeline runs? Thanks!
