### ISSUE TITLE
Add footnote to gov't welcome mat explaining faked planning data

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#422]
For crowns and etc. There currently isn't one (or it's not showing up)

**Comment by rossbm** [comment]
I think we have one already, although we might be missing a closing parentheses:
![image](https://user-images.githubusercontent.com/23534515/70831679-3303c480-1dc1-11ea-8835-8016b50c293c.png)

**Comment by Stephen-ONeil** [comment]
Yeah, we already have it.
