### ISSUE TITLE
Don't show planned spending (in welcome mat, auth exp panel) for Crowns and depts where we've faked it

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#423]
For departments that don't report on planned spending (crown corps, some security-focused orgs), we use the current years' estimates to "fake" their planned spending.

This is done to estimate the government total planned spending more accurately.

However, for dept-level graphs, we really shouldn't show the data that we don't have. Right now we're not showing it for the security-focused orgs ([e.g.](https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/dept/110/infograph/financial)) but we are for crowns ([e.g.](https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/dept/219/infograph/financial))

(related to #422)

**Comment by ktw1016** [comment]
What is the way to check if we're faking for the specific department?

**Comment by ktw1016** [comment]
@cookkate

**Comment by cookkate** [comment]
Subjects where `has_planned_spending` is false. There's a comment in organizational_entities.js that says that pipeline is planning on calculating has_planned_spending based on the data, so exactly how `subject.has_planned_spending` is set might change in the future, but that just means you should be able to rely on it more.

**Comment by ktw1016** [comment]
okay that was my guess, thanks for clarification!

**Comment by ktw1016** [comment]
So I checked on this, it's actually already checking `has_planned_spending` for welcome mat planned spending. In case of `National Capital Commission`, their `has_planned_spending` is `true`

**Comment by GarvinH** [comment]
It seems like this is no longer an issue? I just checked NCC and the `has_planned_spending` is now false.
I also verified other crown corps Canada Mortgage and Housing corp + Canada post which also shows false for `has_planned_spending`.

The other depts CSE and CSIS also remain as false.

Closing this
