### ISSUE TITLE
Add npm audit steps to CI

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#440]
For each project, maybe make status badges for the result. Don't need to result in failed workflows, just warnings.

**Comment by Stephen-ONeil** [comment]
I was originally planning to do this all with a bunch of custom scripts, but decided to do a quick check and this utility library would likely be better than a home-grown solution: https://www.npmjs.com/package/audit-ci

Perhaps add a new CI job that installs that at the root level (don't think we actually want it in the root level package.json/package-lock.json, we'd want it to always install from its latest version), and write a script to run it with `--directory` arguments for each sub-repo. Since we can tell it to only fail for, e.g., moderate and above, then it probably is worth having the entire workflow fail when a vuln is detected.

For branches, it should only run if the package.json for a given project has changed. It should always run on master to catch new vulns in old packages.

If the rate of jobs failing from audit issues is high, we can rethink all this. It is kind of an annoying process to fix all of the audit-alerts some times, and having to maintain an allow list for vulns we can't fix will be a bit of annoying overhead.

Anyway, start with trying to do something using https://www.npmjs.com/package/audit-ci, further ideas or issues will likely come up in the process.

**Comment by GarvinH** [comment]
Now relying on dependabot
