### ISSUE TITLE
More gracefully handle traffic to dead infographics

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#443]
In particular, a fair number of users have been trying to visit infographics for programs and CRSOs that fell out of our window recently. Currently, trying to route to one gets you an error page. 

A better behaviour would be to, for example, fall back to the parent department (or home page?) with a banner explaining why you can't visit the page you were linked to.

Easiest approach would be to bail back home on any failing infographic route. I don't like this because it could hide actual bugs down the road.

Best, but probably the most involved, approach would be to keep a list of recently dead subject ids and their appropriate fallback subjects. Then we'd have something to check against whenever an infographic route fails to match any of the current subjects. On the other hand, that would be a new dataset for the pipeline to produce and yet another thing to maintain. Would it be worth the effort?

**Comment by bill-lliu** [comment]
I believe this is solved with #508 ^ right?
Good to be closed?

**Comment by Stephen-ONeil** [comment]
#508 may not have fixed things, or maybe it will just take time for Google to re-crawl. Dead programs still show up in my google searches at least.

#508 also only fixed one way that this could happen, still want a graceful handling to deal with stale links and bookmarks.
