### ISSUE TITLE
Add Gatsby.js!

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#452]
About Gatsby: https://www.gatsbyjs.org/

How to port over to Gatsby: https://www.gatsbyjs.org/docs/porting-from-create-react-app-to-gatsby/

This would be a massive performance boost

**Comment by Stephen-ONeil** [comment]
Hmm, pre-fetching bundles for potential next-routes could be pretty good! We could also look for ways to implement that without a full Gatsby port.

Their other main selling-point, from an optimization perspective, are smart bundling and image scaling. We already have highly tuned bundling, so there's nothing to be gained there, and we only have one to two png's in the whole project I think. 

What would make it an interesting framework for us aside from a couple performance gains? How hard of a port would it be, and what restrictions might it add? If you want to play around with Gatsby a bit before answering those questions, have a go!
