### ISSUE TITLE
FTEs, and probably some spending, should be displayed as floats, not ints

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#456]
The FTEs are treated at integers by their Table class code, that for sure needs to change to decimal1 or decimal2. Should double check that other data that might contain decimals isn't also being rounded and that the formats used for their display are appropriate

**Comment by GarvinH** [comment]
We could close this after #1001?

**Comment by Stephen-ONeil** [comment]
Quick check over, seems good 👍
