### ISSUE TITLE
Average share for Population by Employee Type is confusing

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#457]
The doughnut chart and accompanying table for Population by Employee Type is a bit confusing since it shows average share across the 5 years rather than the latest year. I was about to use the Report a Problem widget to report that the 3.4% from the top text does not match the chart/table's number of 3.2%

Suggest using latest year for the chart and table. Alternatively, better labeling. Ideally both?

![image](https://user-images.githubusercontent.com/23534515/72289437-23260d00-3619-11ea-89b1-49868da82642.png)

**Comment by bill-lliu** [comment]
I'm going to add a label underneath the chart that clarifies it's the data from all 5 years, might be more clear to users.
