### ISSUE TITLE
Check out this tab component

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#469]
https://github.com/reactjs/react-tabs

My old `TabbedContent` component (think that's what I called it) has always had some jank on IE. Couldn't test these in IE immediately because the demo site wouldn't load in that dinosaur of a browser, but these looked nice in Chrome!

**Comment by Stephen-ONeil** [comment]
If they look the same in IE, then it might be good to switch to them.

**Comment by bill-lliu** [comment]
As nice as this looks, it unfortunately does not work for ie11;
Maybe once we're allowed to scrap internet explorer, we can update the tabs too

**Comment by Stephen-ONeil** [comment]
Ouch. Thanks for checking!
