### ISSUE TITLE
"NaN" displayed when no program level indicators/results

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#471]
Northern Pipeline Energy doesn't have a program level results. As a result, the text in the result drilldown say "In 2018-19, Northern Pipeline Agency Canada seeks to achieve 1 results through 1 Core Responsibility and NaN Programs."

![image](https://user-images.githubusercontent.com/23534515/73079503-56c32b80-3e92-11ea-90c9-2bd84eab017a.png)

**Comment by cookkate** [comment]
Oh weird. How are they allowed to not have program results? Either way, will fix, thanks.
