### ISSUE TITLE
Uniting all the tables?

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#478]
This may possibly be more of a question that a issue:

From what I know, we have a lot of different tables. Results DisplayTable, RPB tables, A11y tables, and just regular panel tables..
I wonder if it would be a good idea to unite all of these to use same table so that when we add a new table functionality, it can be applied to all.

Some related issues: #75 #384 #26 #37 #261 #479

**Comment by cookkate** [comment]
Yeah, we should!

The first thing I was thinking about unifying was the tables used for the gov-level DP and DRR summaries:

https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/gov/gov/infograph/results

Since they're almost the same as the DisplayTable

**Comment by cookkate** [comment]
(also the table view of the panels in the services prototype)
