### ISSUE TITLE
Survey suggestion

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#480]
We want to know what people are looking for; a team member suggested moving from a simple text box to a selection of pre-populated options + 'other' & a text box, to save people typing if they are looking for something standard.

I am not 100% sure we could come up with a list of options that would be both short and detailed enough for what we're looking for, but it's worth considering.

**Comment by Stephen-ONeil** [comment]
Maybe keep the open ended text box but also add something like, "Of the following X broad categories, what 2-3 are you most interested in the InfoBase expanding on?" Then list different data types, fancier visualizations, etc.
