### ISSUE TITLE
Advanced Search design change

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#496]
![20200206_134006](https://user-images.githubusercontent.com/29746626/73967777-90f6e900-48e6-11ea-98d9-d907d90c1cb1.jpg)

<img width="726" alt="Screen Shot 2020-02-06 at 1 30 52 PM" src="https://user-images.githubusercontent.com/29746626/73968352-8d179680-48e7-11ea-814c-17ed0cdbc3d3.png">

How about something like this? This is probably unnecessary but.. if I add panel filter, it might look confusing with two filters in a close by space and this would clarify the search filter usability, also search filter will be usable in the home page as well.

Not sure how customizable `Typeahead` can be, but this could also possibly be implemented alongside the potential changes to our search

related to: #137, #340

**Comment by ktw1016** [comment]
Actually might be implementing something similar to this for filtering panels

**Comment by bill-lliu** [comment]
I like how these look, but maybe make the filter button a slight bit more explicit
like 
![screenshot-docs google com-2020 02 26-16_37_37](https://user-images.githubusercontent.com/26264647/75390497-59aca400-58b6-11ea-984b-4b532ab70c28.png)
(and with a french version of course too)
