### ISSUE TITLE
Broken link to USAfacts.org on the about page

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#519]
Link to the USAfacts partition diagram leads nowhere. Should update if we can find the new link or remove.

**Comment by Stephen-ONeil** [comment]
Especially if the plan to cull the partition diagrams seems likely, I think it's worth dropping.

**Comment by bill-lliu** [comment]
I found it, and they seemed to have upgraded it a lot
https://usafacts.org/visualizations/the-big-picture/

**Comment by Stephen-ONeil** [comment]
Looks about the same as before. Our version was always different in a number of ways. Their popup positions are broken though.
