### ISSUE TITLE
Fractions of years should be displayed as months

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#52]
e.g. in [this](https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/gov/gov/infograph/people/~(panel_key~'employee_age)) graph, it looks weird to have the change in years expressed as an (often small) decimal. This could be a custom format.

**Comment by Stephen-ONeil** [comment]
Discussed, agreed to just remove the part of the age graph text that says "with an average March-to-March change of -0.202 years."
