### ISSUE TITLE
Formatting issue for 'total allocated amount' for HI tags

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#520]
Some HI totals aren't formatting properly.

**Comment by Stephen-ONeil** [comment]
Ugh, those values are stored pre-formatted in the HI lookup files. We could either correct the hardcoded values up-stream (in both FR and EN lookup files, with lang-specific formatting) or use plain numbers in the lookups and format on-client. I prefer the second of those two.
