### ISSUE TITLE
Toss out `client/core/Statistics.js`

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#526]
Part of the old `Table` class/`ensure_loaded` ecosystem, although decently decoupled (which will make it a bit easier to drop).

Currently, most of the `Table` class declaration files in `client/src/tables`, as a side effect, also register `Statistics` instances. Like `Table`s, `Statistics` are registered during the inital load but only lazy-populated by `ensure_loaded` as needed (e.g. when listed in the info dependencies of a panel). 

Pros of `Statistics`:
  - single source of truth for the logic used to calculate common stats for given `Table` instance
  - well integrated with the `Table`, `Panel`, and `ensure_loaded` ecosystem

Cons of `Statistics`:
  - part of the encumbered `Table`/`ensure_loaded` ecosystem, reliance on `Statistics` is an inevitable roadblock to a full move to the GraphQL API
  - has weird, old, API itself. The `calculate` method on each `Statistics` instance registers individual calculated stats with an `add` callback, which itself has strange hidden logic where it prepends things like the subject level on to the name of the key associated with the stats value. The whole thing is full of hidden relationships like that
  - registered stats are primarily used in panels (plucked out of props passed to their render method and then fed on down to `text_maker`s for panel text, mostly). That means their usage is extremely far away from their declaration. I'm sure there's a ton of stats being declared that are never used (maybe the majority). I also think very few stats are ever used in more than one place, so all the downsides of decentralization with no particular capitalization on the potential upsides.

`Panel` instances can exist without `Table` instances (see anything getting all its data from GraphQL), `Table` instances can exist without `Statistics` instances. Stripping out all the `Statistics` code and just calculating values as needed on a per-panel basis is a big, but well isolated, step towards dropping the old `Table`/`ensure_loaded` ecosystem.

**Comment by Stephen-ONeil** [comment]
Likely follow these steps:
  1) remove info dependencies from each panel, switch to calculating required stats locally (either in calculate or render method). Keep an eye out for common calculations across panels, or common patterns and extract the logic to a shared utility function
  2) remove `info_deps` from `src/panels/PanelRegistry.js` itself
  3) see if there's ANY other uses of `Statistics` anywhere else in the InfoBase, replace them if so
  4) remove `Statistics` from `ensure_loaded`
  5) delete the `Statistics.create_and_register` calls in each `Table` declaration file
  6) delete `src/core/Statistics.js` itself

Step 1 will be the bulk of the work. Probably calls for a coordinated team effort!

**Comment by ktw1016** [comment]
😮let me know if you need hand replacing info dependencies
