### ISSUE TITLE
quicklinks to panels on a11y version

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#53]
This would be an easy way to improve the navigation of the text only version. Links at the top of the page could be generated for each panel to allow a user to skip to a particular data table.

**Comment by ktw1016** [comment]
This took awhile to figure out how to do it on Mac VoiceOver but this is how to do it:
1. Turn on Voice Over
2. Press Left+Right arrow to enter Quick Nav mode
3. Press Shift Left or Right arrow to jump between panels

So closing this issue
