### ISSUE TITLE
Planned spending line not connected in "Authorities, Expenditures and Planned Spending"

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#538]
The orange line for planned spending in the "Authorities, Expenditures and Planned Spending" doesn't connect properly from the second to third year.

![image](https://user-images.githubusercontent.com/23534515/75462670-9332ed00-5952-11ea-86a0-823cbda677c0.png)

**Comment by ktw1016** [comment]
<img width="1143" alt="Screen Shot 2020-02-27 at 11 30 28 AM" src="https://user-images.githubusercontent.com/29746626/75464015-97600a00-5954-11ea-8fe4-11bb06a881e7.png">

it actually seems to look fine on my machine. Also checked on IE. Is this live site you checked ross?

**Comment by Stephen-ONeil** [comment]
Kate fixed this before release.
