### ISSUE TITLE
Broken French link to Supps B

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#540]
Currently the "Budget supplémentaire des dépenses (B) 2019-2020" on the Featured Content points to ip address 127:
http://127.0.0.1:8080/build/InfoBase/index-fra.html#rpb/.-.-(subject.-.-'gov_gov.-.-preferDeptBreakout.-.-true.-.-mode.-.-'simple.-.-table.-.-'orgVoteStatEstimates.-.-columns.-.-(.-.-'*7b*7best_last_year*7d*7d_estimates).-.-dimension.-.-'by_estimates_doc.-.-filter.-.-'Budget*20supp.*20B.-.-sort_col.-.-'dept.-.-descending.-.-false)

**Comment by cookkate** [comment]
Thanks for the heads up. Fixed.
