### ISSUE TITLE
Establish generic "Infobase outage" banner text that we can use in the future

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#548]
Suggest:

"GC InfoBase's hosting providers is experiencing a service outage. Portions of the site may be unavailable. We will be back to normal ASAP, thank you for your patience."

**Comment by Stephen-ONeil** [comment]
Darren provided me a couple options, I just haven't gotten back around to building something with them. Will post them here shortly.

**Comment by Stephen-ONeil** [comment]
Version 1:
  en: GC InfoBase is experiencing an outage, resulting in limited functionality. We will be back to normal ASAP, thank you for your patience.
  fr: L'InfoBase du GC est en panne et sa fonctionnalité est limitée. Nous reviendrons à la normale dès que possible. Merci pour votre patience.

Version 2 ("maintenance"):
  en: GC Infobase is down for maintenance. We will be back to normal ASAP, thank you for your patience.
  fr:  L'InfoBase du GC est en panne et sa fonctionnalité est limitée. Nous reviendrons à la normale dès que possible. Merci pour votre patience.

**Comment by Stephen-ONeil** [comment]
#549

**Comment by Stephen-ONeil** [comment]
This was done during #549, see https://storage.googleapis.com/ib-outage-bucket/outage_msg.json
