### ISSUE TITLE
Mini-deploy for pushing status banners

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#549]
Right now the deploy requires all(?) IB services to be up, but as we found out today that's not always the case! It would be nice to be able to push a deploy just of the code in order to e.g. enable a "stuff's broken" banner.

**Comment by ktw1016** [comment]
Can I get a run through of our deploying process next time we deploy, try implementing this and try deploying next few times?

**Comment by Stephen-ONeil** [comment]
@ktw1016 still want to take this on? We could slack call, or even try that VS Code screen share some time.
