### ISSUE TITLE
Make line graphs smart about overlapping line segments

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#557]
I've got some code in the `auth_exp_planned_spending` panel that makes it automatically style overlapping line segments as dashed. I think it's prime for hoisting up to the `NivoResponsiveLine` component as a default setting. Only thing lacking right now is to differentiate the dash array value when more than two line segments overlap (cut that corner in the `auth_exp_planned_spending` implementation since that graph only has two series that could potentially overlap).

**Comment by cookkate** [comment]
Not a bad idea, but I recommend no one start working on this until the #500 is merged or you are not going to enjoy the resulting rebases :)
