### ISSUE TITLE
Year error in French version of estimates comparison

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#566]
![Screen Shot 2020-03-18 at 9 40 43 AM](https://user-images.githubusercontent.com/10406459/76966566-8e7faa00-68fc-11ea-986c-ead409836653.png)
![Screen Shot 2020-03-18 at 9 40 36 AM](https://user-images.githubusercontent.com/10406459/76966572-90496d80-68fc-11ea-8ac4-91e1d26691be.png)

**Comment by Stephen-ONeil** [comment]
Hmm!
