### ISSUE TITLE
Variance explanations for FTEs should show up in the report builder?

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#567]
This one will need some looking into.

A reported issue claims (I think, it's short on detail) that ECCC has a planned/actual variance explanation for FTE counts that is not displayed in the report builder here:

https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#rpb/.-.-(subject.-.-'dept_137.-.-preferDeptBreakout.-.-true.-.-mode.-.-'simple.-.-table.-.-'programFtes.-.-columns.-.-(.-.-'*7b*7bpa_last_year*7d*7d.-.-'*7b*7bplanning_year_1*7d*7d).-.-dimension.-.-'gov_outcome.-.-filter.-.-'All.-.-sort_col.-.-'dept.-.-descending.-.-false)

**Comment by ktw1016** [comment]
Uhm, is this important?

**Comment by Stephen-ONeil** [comment]
If we actually have a variance note for that, it should be in with the rest of the footnotes, yeah. We'll have to see if we have it in the data though.

**Comment by AlexCLeduc** [comment]
It looks like variance explanations show up, but only if you're focusing on a particular subject (as far as I can tell, this is only possible if subject is in the URL). If you go to the RPB from the homepage and use the organization column filter, you'll still only get the gov-level footnotes. 

![Screen Shot 2021-04-16 at 8 38 10 AM](https://user-images.githubusercontent.com/7769215/115025218-15e87580-9e8f-11eb-8bd9-93935f83995b.png)
 
I'm also not sure if CR or program footnotes will show up in the RPB. If they don't, I could see the organization potentially complaining. OTOH, footnotes from multiple levels can end up being redundant.

I'd say we can close this issue, but we may want to rethink how subjects and footnotes work in the report builder.
