### ISSUE TITLE
New Google Lighthouse algorithm, do some spot checks when that's in the wild

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#576]
Breakdown of changes to scoring algorithm
https://calibreapp.com/blog/lighthouse-changes-scoring-algorithm

Still in beta for now
https://github.com/GoogleChrome/lighthouse/releases/tag/v6.0.0-beta.0

**Comment by ktw1016** [comment]
Did some reading on lighthouse, and this guy gives decent description of each metrics:
https://www.reddit.com/r/SEO/comments/eqno31/lighthouse_v6_googles_updating_pagespeed_scores/

Reading through some things, I wonder if adding Lighthouse CI into our Circle CI would add any benefits? https://github.com/GoogleChrome/lighthouse-ci

**Comment by ktw1016** [comment]
related to #602
