### ISSUE TITLE
Add a button to show all graph items in the modal table even if some are toggled off in the legend

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#578]
This is particularly for the graphs with tons of items in the legend and only one enabled by default, tedious to manually click them all on just to get them showing up in the table view

**Comment by Stephen-ONeil** [comment]
I'd prefer the approach of adding a button to the legend to toggle all items on/all but one off, leave the modal table mirroring exactly what's on the graph. It would keep the flow of data to the table simpler and also add the functionality of displaying all items easily to the graph (anti-functionality? in most cases where we start with only one item toggled on we do it for a good reason, haha).

**Comment by ktw1016** [comment]
I'll work on this as part of #584
