### ISSUE TITLE
Add a pivot option to the panel table modals

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#579]
Users could want to switch between key by years with label headers and key by label with year headers (I do for many of the panels, at least).

**Comment by cookkate** [comment]
lol have fun with that

**Comment by Stephen-ONeil** [comment]
Thanks

**Comment by Stephen-ONeil** [comment]
Not going to be a full pivot table feature, just a button to flip the header and key column. Easy peezy.

**Comment by ktw1016** [comment]
I can work on this as part of #584

**Comment by ktw1016** [comment]
Leaving it open for Stephen

**Comment by Stephen-ONeil** [comment]
I think this was originally spawned by an argument about a few specific tables that we'd disagreed on the header vs index layout of. I don't remember which, so we can close it.
