### ISSUE TITLE
Testcafe 1.8.3 slows down browser tests massively, locked to 1.8.2 for now

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#586]
Follow up from #568

Testcafe 1.8.3 produces a >2x slow down in our browser tests. Locked to version 1.8.2 for now.

Quick look at the [1.8.3](https://github.com/DevExpress/testcafe/releases/tag/v1.8.3) release notes has me suspicious of the "--disable-background-networking" flag they turned on by default, as mentioned [here](https://github.com/DevExpress/testcafe/issues/4530#issuecomment-590873962). Total gut feeling. We're using the JS interface to run tests though, not the command line, so this flag's a bit opaque to me (couldn't find it by searching in the GitHub). Documentation's lacking, but maybe it's an undocumented option in the [config file](https://devexpress.github.io/testcafe/documentation/using-testcafe/configuration-file.html)?

If I never get back to this, then this issue is just a reminder of why we're locked to 1.8.2. Give it a couple versions and try unlocking, see if the slowdown is still a problem.

**Comment by ktw1016** [comment]
Just quickly comparing CI tests from webpack branch (testcafe@1.94) with any other branch, seems like it takes around similar time.

For reference, [here](https://app.circleci.com/pipelines/github/TBS-EACPD/infobase?branch=webpack5) is CircleCI link for webpack branch to compare with any other tests
