### ISSUE TITLE
MediaQuery components with multiple direct descendants 

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#589]
Seems a MediaQuery component with multiple direct children will render them wrapped in a div. When not desired (why would it be...) you can manually wrap the children in a `Fragment`.

At some point we should double check that this little gotcha isn't messing us up anywhere.

Maybe write a linter rule to warn about it, or at least add it to the project wiki as something to be aware of.

**Comment by GarvinH** [comment]
Apparently this has been addressed in the newer versions of react-responsive.

Doing so will also require an update in react however (not sure if the code is ready for that though). Should probably done with or after #739.

The newer version of react-responsive also added hooks which should help clean up #759.
