### ISSUE TITLE
Potential typeahead replacement

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#590]
Only looked at the demos [here](http://react-autosuggest.js.org/), but they look good. The custom example makes me guess it has a much more friendly API than our current dependency, and I'd love to rewrite against a library I don't have to hack around.

**Comment by ktw1016** [comment]
Wohoo this looks great, one thing that I don't like is the `Project Status`:

```
Looking for maintainers!

Unfortunately, I don't have the time to maintain this project anymore. If you are interested to help, please reach out to me on Twitter @moroshko.
```

**Comment by Stephen-ONeil** [comment]
Damn. Well, if I look at the code and like what I see then maybe I'll offer to do some light maintenance, haha.
