### ISSUE TITLE
Removal of the word "l'effectif" from French pages.

### ISSUE THREAD

**Issue by darren-coughtrey** [TBS-EACPD/infobase#594]
Change the word "l'effectif" to "personnel" across the board on the French pages. Apparently "l'effectif" has some outdated military connotation, and we use the word "personnel" in the English text anyway.

**Comment by GarvinH** [comment]
![image](https://user-images.githubusercontent.com/25855114/85154151-15f2f700-b225-11ea-9ed2-d21316e9a8e5.png)

![image](https://user-images.githubusercontent.com/25855114/85154547-94e82f80-b225-11ea-911f-121d1450f877.png)

So I've tried recursively replacing them. Upon investigation, I found a scenario where l'effectif was not replaced???

I also found the words "Les effectifs" which I'm not sure if they should be replaced as well.

**Comment by GarvinH** [comment]
Turns out that the scenario where it was not replaced had the different ' apostrophe. Most likely the work of a word/excel editor changing it.
