### ISSUE TITLE
integrate prettier

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#597]
Here's what we need before we call this done and start formatting everything

1. an npm command to format everything, we'll need to run this at least once for each active branch. This can either be separate client/server/email or just one 🤷 
    * There should be a similar "dry-run" command that we can run to make sure our code already passes formatting
2. a strategy to minimize the impact of merge conflicts on existing PRs. I'm hoping if we run the above "format everything" command on master and the PR separately, then we won't get any worse conflicts than what we started with. Note that rebasing becomes difficult so we can either squash or just have plain merges
3. a pull-request level CI step that "fails" when the dry-run formatting command returns non-null changes
4. VSCode integration

Note that it's popular to use git hooks for this kind of stuff, but I'd prefer we _don't_ use a pre-commit hook because it becomes impossible to commit staged changes without also commiting unstaged changes in the same files. I like to tinker with commits too much for this not to piss me off

**Comment by ktw1016** [comment]
Can this be closed?

**Comment by AlexCLeduc** [comment]
🎉
