### ISSUE TITLE
About time we clean up the index.hbs.html files and associated code

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#60]
We tend to put this off constantly, because it's painful to deploy these specific files through Comms, but there's at least some stuff in there that's stale.

For example:
  - [ ] the footer_list content is a mix of hardcoded footer links from the template and run-time footer links from InsertRuntimeFooters. Should get rid of the template links and do them all at runtime, because that's a lot more flexible for us
  - [ ] ... the id of that footer list area is `#footer_survey_link_area` but we've now moved the survey link out of it (should have given it a more generic name in the first place, it stoped being just for the footer link very quickly). Annoying to leave it with the misleading id, but not worth pushing the html files through comms just for this

**Comment by GarvinH** [comment]
closing in favour of above
