### ISSUE TITLE
department DRR donut labels messed up 

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#604]
![Screen Shot 2020-05-05 at 8 41 43 PM](https://user-images.githubusercontent.com/7769215/81128993-d7bda480-8f10-11ea-9a32-af3f5372d040.png)

**Comment by Stephen-ONeil** [comment]
Huh, hadn't seen that before, but rebasing a commit that references an issue seems to keep re-logging the reference.
![image](https://user-images.githubusercontent.com/11301919/81229148-5c65fc80-8fbd-11ea-81b7-e0c7baa2958f.png)
(screen shot in case this is a caching thing or GitHub retroactively figures out that only one of those references still exists)
