### ISSUE TITLE
Try and show chart axis even if all items are disabled

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#607]
We previously stopped users from de-selecting all items in a graph, but it's now possible with the new select all/none legend controls on certain graphs. Can lead to broken looking panels.

Big white space left where the graph would be,  example from a mobile layout (better than the space collapsing in, worse than there still being something there):
![image](https://user-images.githubusercontent.com/11301919/81227006-b6fd5980-8fb9-11ea-96e6-400521af800f.png)

Probably a fair bit of work, potentially hacking around how nivo works. Might be able to make it more straightforward to achieve this in the process of doing #599, if I plan for it while standardizing the wrapped nivo component APIs.

**Comment by GarvinH** [comment]
Proposal: remove "None" as a button and replace it with "Reset" button which will reset to the on page load default.
I don't really see a point in showing an empty graph.

**Comment by Stephen-ONeil** [comment]
The "None" button is partially so that a user who wants to only display one particular item on a graph has a reasonable way to do that. The alternative being to manually deselect all but the one item you want to show. Of course, it also acts as a sort of un-do for the "All" button (although a "Reset" or maybe "Default" button might arguably be better for that!).

We've always had the behaviour that if there is only one selected then that last item can't be deselected. The select "None" button bypasses that check. We could choose to apply that rule to the "None" button, making it a "One" button, but that would be weird (forcing the users to recon with what should be totally internal logic) and we wouldn't have a particularly good way to pick that "One" that gets shown (of all the options, the first item in the list feels like the closest to right). Plus, a user who wants to only see some other item would then have to toggle that one on just so they could go back and toggle off whatever the "one" shown was.

Perhaps an alternative is some sort of "solo" feature to temporarily show only one item. That'd be a complicated UI though, either a button that then changes the behaviour of the next click in the graph or maybe a second radio button control for each option in the menu. Or a button that turns all the check boxes in to radio buttons, so that only one can be selected at a time? None of these are hard to implement, but none of them seem intuitive enough for me to want to shove them at our users.

If you can think of and implement a good "solo" feature then I think we can definitely consider dropping the "None" button and switching to "Reset"/"Default"/whatever.

**Comment by Stephen-ONeil** [comment]
Although I guess that then leaves users who want only two, etc., specific items to show potentially having to manually deselect all other options still. It then means the choice of default selected items would need to account for that, e.g. defaulting to all items in a graph that can have potentially 10+ items would make it too painful to select any specific smaller set of items.

May have just talked my self in to and then back out of the reset + solo idea. Not that I was convinced the solo function could be implemented in a clear enough fashion.

I'm back to just wanting a "none" button that doesn't look like something broke when you click it.
