### ISSUE TITLE
rainbow PDF, blank PDF, half-cut PDF

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#616]
1. Rainbow PDF: when single page PDF becomes too long, Chrome doesn't seem to render it well. Although opening it on Adobe works fine

2. Blank / Half-cut PDF: Can't replicate this issue. (Laura mentioned)

**Comment by Stephen-ONeil** [comment]
Closing, 1 seems to be a browser bug and 2 can't be recreated/hasn't been reported in a long time.
