### ISSUE TITLE
DisplayTable in RPB, error on removal of sorted column

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#620]
Worked this out from a prod error logged to analytics, so some urgency to fixing it!

Easy to reproduce:
  - go to the RPB and enable two columns of data
  - sort by one of the two
  - disable the currently sorted column
  - crash :(

**Comment by ktw1016** [comment]
ah BAM

**Comment by ktw1016** [comment]
Actually currently working on new ways of adding/removing columns for rpb, but I'll hotfix this one until that gets worked on
