### ISSUE TITLE
Dept infographic SEO

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#622]
Dept infographics look to still be indexed primarily by page title, which is still he legal title instead of the applied titled. For example, searching for "InfoBase Health Canada" mostly shows the PHAC infographic link (because it's legal title includes "Health Canada", while Health Canada's legal title does not, being "Department of Health"). Double check what the actual titles of those routes are and adjust. Maybe ensure that the route descriptions include both titles.

Possible that this is just stale indexing from before I switched everything to default to the applied title, look in to that too.

Side note, this came about because google analytics logged an error thrown by a user trying to visit a malformed Health Canada infographic link, but it shows the referrer of this link being Google. Couldn't find the malformed link from my own Google searching though, so will need to look in to that from a different direction (if that sort of error ever shows up in our logs again).

**Comment by GarvinH** [comment]
Did a google search and doesn't seem to happen anymore 🤷
