### ISSUE TITLE
form auto-fill on table filter

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#624]
This is kind of weird

<img width="1379" alt="Screen Shot 2020-05-19 at 1 36 15 PM" src="https://user-images.githubusercontent.com/7769215/82360062-d1cac780-99d6-11ea-82e2-6a54df381824.png">

**Comment by ktw1016** [comment]
uhhh lol I actually never get this

**Comment by Stephen-ONeil** [comment]
Ha, don't think I've gotten that either. We should slap a `autocomplete="off"` on all of those, probably.

**Comment by AlexCLeduc** [comment]
I actually can't reproduce it anymore lol
