### ISSUE TITLE
Add method of getting in touch to the report a problem widget

### ISSUE THREAD

**Issue by darren-coughtrey** [TBS-EACPD/infobase#643]
There is no option in the Report a Problem Widget for users to receive an answer to potential inquiries they have about trouble with the site. There is an opportunity to use the InfoBase feedback inbox as a means of direct contact, once we reclaim access to that inbox.

**Comment by Stephen-ONeil** [comment]
No current plan to make the Report a Problem widget two-ways. It's very specifically meant to be anonymous.

We can suggest that users who want two way communication on bugs/suggestions come to GitHub and open an issue here. We'd just need to double check our code of conduct and add an issue template.

Alternatively, direct them to the contact info from #651.
