### ISSUE TITLE
Lack of instructional material

### ISSUE THREAD

**Issue by darren-coughtrey** [TBS-EACPD/infobase#646]
There is an option to report issues on the page. However, there is no instructional material other than the “About” page, which does not help the user better use GC InfoBase. 

This issue may be addressed to some extent by the new FAQ page, but could be worth more consideration.

**Comment by Stephen-ONeil** [comment]
Related to #647

**Comment by Stephen-ONeil** [comment]
Only vaguely different from #647, closing in favour of that.
