### ISSUE TITLE
Use full dept names in titles for CR/programs rather than acronyms

### ISSUE THREAD

**Issue by darren-coughtrey** [TBS-EACPD/infobase#649]
Relates to issue #644 regarding the general use of acronyms, but specifically to their use in Titles.

For example, some participants were confused about whether the content they found was specific to Health Canada as they did not necessarily see or understand the meaning of “(HC)”."

**Comment by ktw1016** [comment]
Is this already fixed? I do remember seeing (HC) previously but as now I checked, I couldn't find any programs/CRs with titles (HC) at the end. Closing as I can't find any examples but please re-open if it's not true @Stephen-ONeil @darren-coughtrey
