### ISSUE TITLE
Change 'Contact Us' footer to point to TBS public enquiries

### ISSUE THREAD

**Issue by darren-coughtrey** [TBS-EACPD/infobase#651]
Possible connection to #643 

Currently, the "Contact Us" link in the footer directs to a general GoC departmental contact page. 
Can we switch the FIP footer's contact us link with a link to our own "contact us" type page with more TBS/GC InfoBase specific contact info?

**Comment by Stephen-ONeil** [comment]
If we do decide to make an email public, it should go in the FAQ as well.
