### ISSUE TITLE
Add table of contents links to infographics

### ISSUE THREAD

**Issue by darren-coughtrey** [TBS-EACPD/infobase#659]
UX participants felt the "on this page" feature, which was included in the Testing wireframes, was helpful to understand what was exactly on the page before scrolling through it all. Nearly all participants attempted to navigate via this table of contents.

The idea is to a list every panel at the top of each infographic so users can click, and quickly navigate to the desired graphic. Consider this addition, but weigh it against the page getting too cluttered.

**Comment by ktw1016** [comment]
Hmm, I wonder if #529 can be an alternative to this one?

**Comment by Stephen-ONeil** [comment]
Doing this would close #53
