### ISSUE TITLE
Some 2020-21 indicators not showing last year's target properly

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#663]
This is affecting an indicator for Statistics Canada named "Percentage of users satisfied with statistical information". They use this indicator at the CR level, as well as multiple times at the program level. The indicator(s) also existed in DP 2019-20, with a minimum target of 80%. The 2019 indicators show up in InfoBase as well as the CSVs. For example, at the CR level both the 2019 and 2020 versions of the indicator have a `stable_id` of  "DR-2027" in the CSV. 

![image](https://user-images.githubusercontent.com/23534515/84819756-8d871300-afe6-11ea-9d7b-96681db41c95.png)

**Comment by ktw1016** [comment]
Hmm, I'm not 100% clear what the problem is, I'll take a closer look into the email when i get my new tablet
