### ISSUE TITLE
Gross and Net Planned Spending table needs polish

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#678]
![image](https://user-images.githubusercontent.com/11301919/86660500-c9dfda80-bfb8-11ea-984f-31e39f3641e3.png)

 - Inconsistency between "Planned Spending (net)" and "Gross planned spending", both in structure and capitalization
    - this may have been partially on purpose, because net is what we usually mean when we say planned spending and this may have been done to try and communicate it that way (but it just looks sloppy)
  - Ordering feels off. With this ordering, column 1 = columns 2 + 3 - 4, but I think you'd expect the final column to be the product, not the first. Maybe order it either `gross | special | revenue | net` or `revenue | gross | special | net`?
    - could be good to some how further communicate the formula happening in this table visually (make revenue numbers red, net or gross some third colour?)
  - "Planned Specified Purpose Account Spending" should be hidden if it's zero in all years, it's a weird special case that very few departments have if I remember right (someone look at the data and check me on that). Annoying to have one super wide column in the middle of the table if it's going to be a bunch of zeros more often than not

**Comment by ktw1016** [comment]
Just a minor correction, "Planned Specific Purpose Account Spending" seem like a negative number. So this is another subtraction

**Comment by Stephen-ONeil** [comment]
In the way we tend to present this stuff, spending is positive and revenue is negative (since what we care about is the net spending). "Planned Specific Purpose Account Spending" is still spending, so it would only be subtracted from the net spending *if* the values in the csv themselves are negatives.

**Comment by ktw1016** [comment]
That seem to make sense but numbers don't work out, check out CBSA numbers here #679

**Comment by Stephen-ONeil** [comment]
HA, the glossary definition we have doesn't help either, makes it seem like it could be either revenue or spending: http://dev.ea-ad.ca/master/index-eng.html#glossary/SPA

Ok, I'm not sure then. Nick would know for sure though, perhaps we should get his feedback on this panel before we merge any changes to it.
