### ISSUE TITLE
DisplayTable CSV issues

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#687]
Got this through the report a problem form recently:

"The downloadable CSV file includes comma separators, but the department titles also include commas, which causes column misalignment. Not to mention that Excel does not recognize accented characters from the CSV file."

Reported from the RPB.

Wrapping cells containing commas in quotes is straightforward (we don't?), but supporting Excel on windows through the default download button might be tricker. Excel/windows have some tricky encoding issues that are heck for accents.

**Comment by ktw1016** [comment]
I can't replicate column misalignment (tried Edge, Chrome on Windows and Chrome, Safari on Mac). Excel not recognizing accented characters from CSV file should be fixed by #732
