### ISSUE TITLE
weird viz idea

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#69]
Ok this is kind of bananas, fair warning:

- Take all the programs (maybe for a specific ministry or tag)
- cluster by Sobj breakdown (% of spending to each sobj)
- make a heatmap, where X is year, Y is program, colour is PA spending / planned spending

it will be awesome I swear

**Comment by Stephen-ONeil** [comment]
Would be cool, but I intend to scale back on the "cool visualization" side of the InfoBase until we've got a solid, usable and useful, site.
