### ISSUE TITLE
Unclear which dept when looking at the Single Indicator page

### ISSUE THREAD

**Issue by sarahcharaf** [TBS-EACPD/infobase#709]
For example, I was sent this link but was unable to determine which department this indicator belongs to.

https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#indicator/PROGRAM-dr18-2705

Can we indicate it somewhere - maybe in the breadcrumbs?

**Comment by ktw1016** [comment]
haha, I actually noticed this too when I was working on service inventory because I referred to single indicator pages. I'll work on this
