### ISSUE TITLE
Ensure old report builder urls resolve reasonably

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#716]
Changed a lot recently (e.g. no more simple vs granular views). Dig up some old links and make sure they aren't totally broken. Might need to write some extra rules to translate old urls to new equivalents.

**Comment by ktw1016** [comment]
Just checked, everything works (goes to the correct table and applies the correct dimension) but not the same department or selecting columns (as expected since it is now baked into DisplayTable)
