### ISSUE TITLE
The fate of the report builder and tables

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#75]
Right now it might make sense to close the report builder and rewrite tables, but we want to keep the RPB's functionality, including:

1. easy access to the raw data
1. some basic spreadsheet capability (sorting/filtering on columns)
1. show the data for one dept/cr/program
1. holding additional data that isn't anywhere else (e.g. QFRs)
1. allow linking to specific data

One possibility is to separate the functions into a panel-specific "show raw data" modal (which handles the "show the data for one dept/cr/program" requirement), and have the other three handled by a simple table displayer. (name TBD)

The question remains of what a table should be internally. Is it just an object with stuff like names and footnotes, or does it have data? If it has data, will that come from the API or from csvs? What to do about column definitions (including formatting)?

What will be repeated every time for a new panel and what will we collect into some table-like objects? Possibly a 'dataset' object (will also have links to open data).

**Comment by Stephen-ONeil** [comment]
#554 is going to get rid of a lot of the RPB issues and further reduce the importance of Tables. Won't fully settle this, as we'll still _have_ Tables, but it's a step (and a big one on the RPB side).

**Comment by Stephen-ONeil** [comment]
Easy answer, the fate is death for Tables, a new (Table free) life for the RPB. Just going to naturally go this way as we port to the GraphQL API.
