### ISSUE TITLE
Year handling

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#78]
Two sort of related issues:

- We delete the current year during the half-year period between DPs and PA/DRRs. This is suboptimal.
- Each time a data update happens that moves the year forward for that dataset, there needs to be a manual update of the years for that dataset. Also suboptimal. Years are hard to match between datasets (what does budget year 2018 match to in public accounts years?)

**Comment by Stephen-ONeil** [comment]
Closing as this will be a problem solved by porting all data to GraphQL, moving years in to data. Trialed this approach with the covid data, and it's solid.
