### ISSUE TITLE
Where did the select columns button in RPB go?

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#781]
Maybe I'm just forgetting how this works, but isn't there supposed to be a "select columns" button? This is on master

<img width="1269" alt="Screen Shot 2020-09-14 at 7 40 53 PM" src="https://user-images.githubusercontent.com/7769215/93148595-36b2d780-f6c2-11ea-8fd1-4a5769967f1e.png">

Maybe I asked for this with the display table API changes 😆

**Comment by ktw1016** [comment]
Where's Wally?

**Comment by ktw1016** [comment]
It's supposed to be there, there was a slight error on the logic with deciding whether to show this util or not
