### ISSUE TITLE
Use different eslint rules for prod builds than in dev

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#808]
Specifically the `no-debugger` rule. Currently, the project settings run eslint fix on save, so to have a debugger statement during dev you HAVE to set the line to be ignored by eslint... at which point why have the rule? 

We should be able to use debugger statements in dev without flagging them as ignored. Only prod builds should complain about them being left in.

**Comment by ktw1016** [comment]
Just checking it now, eslint now doesn't auto remove `debugger` statement on save. I think maybe moving eslint to root folder fixed that? This issue can be closed if that's the case (unless there are more rules to enable only in dev)

**Comment by Stephen-ONeil** [comment]
Huh, it's still removing my debuggers. Can you rerun `npm ci` in the repo root, and maybe restart your eslint plugin? It might be that your eslint is broken currently if you hadn't done since I merged the config cleanup branch, I think I forgot to mention that to you and Garvin.

**Comment by ktw1016** [comment]
Ah, had to do reload window on VSCode, and it's removing it now😒
