### ISSUE TITLE
Handle broken links better

### ISSUE THREAD

**Issue by ktw1016** [TBS-EACPD/infobase#822]
If the panel part of the link is broken, just direct them to whatever infographic page it should be

If the whole thing is broken, just redirect them to #home

Maybe a banner to let them know they were redirected because link is broken

**Comment by GarvinH** [comment]
related #443 ?

**Comment by ktw1016** [comment]
Oh yeah, this one seems redundant. Thanks!

**Comment by Stephen-ONeil** [comment]
Semi related! #443 is a subset of the second case ("whole thing is broken", which usually means the subject can't be found, which is what happens with dead subjects in #443). 

The first case, where just the panel args portion of the url fails to parse and throws an uncaught error, is unrelated.

**Comment by Stephen-ONeil** [comment]
Closing this could close #443, although #443 proposes a more tailor-fit solution for dead CR/programs. Might be worth doing both.
