### ISSUE TITLE
Eliminate globals

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#840]
`inject_app_globals.side-effects.js` should be gutted. Not convinced anything should be on `window` at all. Global constants/env vars should be moved to their own module. React, D3, and Lodash could be imported as needed. D3, if not even Lodash (harder), could move to importing only what's required, instead of importing the whole library. `feature_detection` and the colour globals should never have been globals in the first place (just dev laziness there).

These are essentially all dependencies that we're not letting webpack help us with, so if we get out of it's way we'll benefit more from current/future optimizations too. Maybe somewhat minor in the end, but it'll help the entry point bundle and any optimization to the initial load time is worth it.

Only exception is `_DEV_HELPERS` which a) could use a rename and b) maybe shouldn't exist in prod (I mostly use it on the master dev link anyway). It's effectively lazy-loade, since things like subject only assign to it as they initialize, so it's not part of the optimization argument.

**Comment by ktw1016** [comment]
okay, so are you suggesting to use webpack global constants? In that case, we'd have to allow undefined variables in eslint which isn't favourable.

**Comment by Stephen-ONeil** [comment]
No, there'd be one module that exports the webpack env vars. The difference is just that, instead of `window.lang` etc everywhere, you'd import `lang` from that module.

Only eslint change would be dropping the whole globals section.
