### ISSUE TITLE
Reconsider net promoter style question in the mini-survey

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#842]
Might not be measuring what we really care about. Give it some time, consider switching it out for DPs.

**Comment by ktw1016** [comment]
I think the mini survey was a good idea since we've been getting way more number of survey results.

I do wish that there was actual user input as to why the user gave a specific rating tho, so maybe we can add a user input box

**Comment by Stephen-ONeil** [comment]
Until someone has a good enough idea to be worth a data discontinuity, now that we've got two rounds in using the current style of question, let's not force ourselves to change it.
