### ISSUE TITLE
improve UX around survey "maybe some other time" option

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#845]
It looks like it can show up every 3 minutes, and even more frequently if you have multiple windows/tabs open.

I think it should wait days, and that the logic should work independently of windows/tabs.

One way to do this would be to use `localStorage` 

1. when showing the banner, store the store the current time, e.g. `bannerLastShownAt`
2. only show the banner if a certain amount of time, anywhere between 1 and 5 days 🤷 , has gone by since `localStorage.getItem('bannerLastShownAt')`

If I recall correctly, the current banner uses a `setTimeout` with 3 minutes and then shows the banner.  I think 3 minutes is a reasonable amount of time to wait to show the banner for any particular tab.  If we throw in the `localStorage` check in this `setTimeout` block, we get the added benefit of ensuring other tabs haven't already dismissed the banner during that 3 minute wait.

**Comment by Stephen-ONeil** [comment]
Aha, did a hotfix (6a1c801) for this when you mentioned it on slack. Deployed for a bit now. Are you still getting it more frequently than expected when opening multiple tabs?

**Comment by AlexCLeduc** [comment]
Sweet, I hadn't noticed! The survey bugged me this morning but I guess it only bugged me once

**Comment by Stephen-ONeil** [comment]
Let me know if you are seeing it more than you'd expect! When it was up last year, some people were saying they saw it repeatedly, even after answering or dismissing it. That may have been specific to IE 11 on TBS machines though, and if IT'd broke localStorage there I really wouldn't be surprised.
