### ISSUE TITLE
Getting an error on People infograhic for ERC (296)

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#846]
On production (and drr dev link), following URL giving an error:
[https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/dept/296/infograph/people](https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/dept/296/infograph/people)

**Comment by ktw1016** [comment]
Fixed by #847
