### ISSUE TITLE
Review long relative imports, leverage absolute imports

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#868]
Great that we have absolute path imports working now. Lots of imports that look like `../../../...` that we should hunt down and clean up. Even better, modules like `src/panels/panel_declarations/shared.js`, that mostly just import modules to reexport them locally, can _finally_ die!

**Comment by Stephen-ONeil** [comment]
Way I see it, we can think of anything under the directory `X` in `src/X` as being "local". "local" modules could (should?) probably import each other via relative imports. If module `x.js` in `src/X/x.js` wants to import from `src/Z/z.js`, it should probably use an absolute import.

Of course, unless we find a linting plugin for this, it's just an informal rule and will probably never be totally consistent. I also haven't thought too long about it, so any other opinions are, as always, welcome!

**Comment by AlexCLeduc** [comment]
After a manual cleanup, we can add the https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-relative-parent-imports.md rule to ensure this practice stops

**Comment by ChetanMandur** [comment]
Absolute imports have been implemented, making new issue regarding re-export files.
