### ISSUE TITLE
Incorrect transfer payments per capita at Canada level

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#873]
The mini bar chart that appears beside the map of Canada shows incorrect per capita transfer payments for all of Canada. I think that the per capita amounts for each province and territory are just being added, leading to $194,000 in transfer payments per person being displayed, which is far too high.

Canada wide per capita amount needs to be recalculated as `sum of transfer payments / sum of population`. Alternatively, the bar chart could just be dropped.

![image](https://user-images.githubusercontent.com/23534515/106025946-43473380-6097-11eb-90cf-f79e58161e49.png)

**Comment by Stephen-ONeil** [comment]
Ouch! Good catch, thanks! Fixed, will deploy shortly.
