### ISSUE TITLE
Extract search logic from Typeahead

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#880]
Follow up on #815, refactor the `Typeahead` component to extract the `/search` specific logic from it and make the component useful on its own.

**Comment by GarvinH** [comment]
#880 may help simplify some of the work

**Comment by Stephen-ONeil** [comment]
To clarify, I think completing #8080 might make revisiting #881 worthwhile, as doing this right should simplify the `Typeahead` component itself and make it easier to work on.
