### ISSUE TITLE
Issues with new search

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#892]
Hi,
I have been having some trouble with the updated search bar. I'm not always getting results when I expect some. For example, searching for "treasury" returns no results:
![image](https://user-images.githubusercontent.com/23534515/107705272-7808dc80-6c8c-11eb-9e32-805ff0d98b64.png)

Same for "tbs":
![image](https://user-images.githubusercontent.com/23534515/107705345-940c7e00-6c8c-11eb-9255-6548878f3fe5.png)

But when I refreshed the page, it works:
![image](https://user-images.githubusercontent.com/23534515/107705429-b56d6a00-6c8c-11eb-9986-879916c8568b.png)

It seems to be triggered by some combination of clicking outside the search box and deleting characters. Once it triggers, it seems like a refresh is necessary to get the search working again. (This is on Edge)

**Comment by Stephen-ONeil** [comment]
Can't seem to recreate on Chrome. I'll try Edge in a bit.

If you have a chance, please try finding a consistent way to recreate it, and maybe see if you can make it happen in some other browser.

Thanks!

**Comment by Stephen-ONeil** [comment]
Not finding a way to make it happen on Edge either. Was this on master, a particular dev link?

**Comment by rossbm** [comment]
This is on master (and also the people2020) branch. I have been able to replicate it on Edge, both on my tablet and personal computer. Also can replicate on Chrome, but doesn't seem 100% consistent on Chrome.

- Type "tbs" into the search box
- Click outside search box to remove focus
- Highlight the text in the search box, replacing it with "cra"
- Nothing pops up
- Highlight the text again (or use backspace) and type in "agriculture"
- Nothing pops up

Once you do that, the search stops working until you refresh.

**Comment by Stephen-ONeil** [comment]
Hmm! Ok, @ktw1016 please look at this with Ross, I've got too much dropped on my plate as of this morning.
