### ISSUE TITLE
Outdated Nivo version, large number of React warnings

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#910]
We're still locked to Nivo `0.52.1`. Now that we're on React 17, it's giving off an overwhelming number of React dev tool warnings for deprecated lifecycle methods. Nothing will break until React 18, but it's going to make it harder to see any new console warnings in the meantime.

Options:
  - [ ] upgrade Nivo
    - ... no migration docs, tons of undocumented and breaking prop changes
    - Nivo is STILL pre-1.0, so this won't be the only time we have to do a blind-upgrade 
    - allows/requires us to also upgrade D3 to the latest version at the same time
  - [ ] drop Nivo for a new chart library
    - unknown effort ceiling, but at minimum this is a very big task
  - [ ] ... use `patch-package` to add `UNSAFE__` to the deprecated lifecycle methods
    - extremely easy, relative to other options
    - delays the inevitable task of dealing with Nivo
    - React 18 proof, for these breaking changes at least...
    
Well, almost definitely going to be option 3, but I'd prefer we at least take a stab at option 1.

**Comment by ktw1016** [comment]
I'll take a stab at upgrading Nivo
