### ISSUE TITLE
About this organization - Lines breaks in names of fields and order of fields

### ISSUE THREAD

**Issue by rossbm** [TBS-EACPD/infobase#911]
There's a lot of white space between the fields listed "About this organization". It is partly caused by lines breaks in the names of fields. In the below example, "Appropriate Minister(s)" is split across two lines, and so is "Description/ Raison d'être". (This is on Edge).

I think that the ordering of the fields could be improved, with the more interesting/important/used fields appearing closer to the top. I don't have strong opinions, but I think that "Description/ Raison d'être" should be one of the first fields.

![image](https://user-images.githubusercontent.com/23534515/108418679-9415fc00-71ff-11eb-8b3b-131948470969.png)

**Comment by ktw1016** [comment]
Hey Ross, I was trying it out on Edge and couldn't replicate this. The title of each fields are on same line as it should. Was there anything specific you did to recreate this? And would you be able to tell me at what pixel you saw this happening? (On IE, press F12. On the right side of the browser, you'll see dev tool. Drag this to expand, you'll see the exact pixel of the width of the view port on the top left of the dev tool)

**Comment by rossbm** [comment]
Sorry, I'm not certain what browser I was using. I can't recreate it on Edge, Firefox or Chrome. 

Feel free to close the issue

**Comment by ktw1016** [comment]
👍
