### ISSUE TITLE
Revert from custom fcol's to bootstrap col's

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#916]
I just remembered why we had out own `fcol` grid system... Bootstrap 3 mostly used floats for its grid layout, and we wanted flexbox. Bootstrap 4 uses flex for its column system though!

If I'd remembered, this potentially could have been part of the bootstrap 4 migration. On the other hand, I'm sure it won't be entirely straight forward, there's lost of differences between the two and we may have lots of fiddly little style rules spread about that could be tied to the current `fcol` implementation. Would require a lot of careful checking.

Note that this would essentially be a hard-decision to stick to using bootstrap. The fact that we were mostly switched to an alternate grid system was a big part of why dropping bootstrap altogether was (and is) an option for us. Just something to keep in mind.

**Comment by ktw1016** [comment]
Hmm, I think main benefit to start using bootstrap at the beginning of a project lifecycle is that they come out of the box so that they don't have to be custom. For us, the only benefits of reverting back to bootstrap is that they'll maintain the cross browser compatibility for long term. Now that we're fully using our own fcols, I don't think it's much worth it IMO

**Comment by Stephen-ONeil** [comment]
If we plan to stick keep bootstrap around, then it'd be better to lean in to that. New devs will need to look at the bootstrap documentation for other things, might as well leverage the bootstrap grid system docs too (as opposed to the `fcol`s, which have no documentation and likely have minor differences from bootstrap's implementation).

**Comment by ktw1016** [comment]
yeah true, documentation is a big plus

**Comment by Stephen-ONeil** [comment]
Dropping "needs-debate" label. Let's drop out fcol's and standardize on bootstrap. Doesn't seem like we'll be fully dropping the framework.
