### ISSUE TITLE
Panel refactor

### ISSUE THREAD

**Issue by cookkate** [TBS-EACPD/infobase#92]
This is going to be a bunch of work but the payoff should be worth it. We'll have to go through each panel and

- [ ] offload statistics calculation to the actual panels. Maybe will be worth trying to centralize stats but probably not.
- [x] calculate table form for each graph, related to #75

**Comment by Stephen-ONeil** [comment]
I think "calculate table form for each graph, related to" is talking about essentially, #500?

**Comment by Stephen-ONeil** [comment]
And the first bullet is a duplicate of #526
