### ISSUE TITLE
typeahead menu closing prematurely

### ISSUE THREAD

**Issue by GarvinH** [TBS-EACPD/infobase#926]
If the next/previous 30 items button brings us to the last/first page of the paginated sequence, the typeahead will automatically close itself for some reason

example: 

1. type in `tre` into the typeahead, and go to the middle page
2. selecting next/previous then will close the typeahead

I'm close to getting a working version of react-virtualized for the typeahead (i think?) which means we might be able to trash the pagination which would also mean we don't need to fix this issue

**Comment by ktw1016** [comment]
Garvin's true love for react-virtualized

**Comment by ktw1016** [comment]
Do you mean middle of first page, or just going to 2nd page? And what do you mean next/previous?

**Comment by GarvinH** [comment]
for next/previous, i mean the 

![image](https://user-images.githubusercontent.com/25855114/109831755-b9e2ce00-7c0d-11eb-9812-bb838b4ca833.png)

buttons.

But yea, going to the 2nd page (and pressing previous 30) or going to the 2nd last page (and pressing next 30) will cause the menu to close on its own

**Comment by ktw1016** [comment]
oh okay, seeing it now. Way too many problems with this typeahead

**Comment by GarvinH** [comment]
closing because after #921, this no longer applies
