### ISSUE TITLE
Julie's suggestion for org About infographic changes

### ISSUE THREAD

**Issue by Stephen-ONeil** [TBS-EACPD/infobase#93]
![Capture](https://user-images.githubusercontent.com/11301919/57779511-32ecfa80-76f4-11e9-96b0-ff71cc9a41b1.PNG)

**Comment by cookkate** [comment]
The reason to do this is because the about panel is where you land if you search for an org, so it makes sense to have a "welcome mat" type panel here.

**Comment by Stephen-ONeil** [comment]
The point about this being useful because it's where the search sends you is valid. Don't know if I want to clutter the about panel with this though. Perhaps the pre-bubble state of an infographic (e.g. http://dev.ea-ad.ca/master/index-eng.html#orgs/gov/gov/infograph/) should have a cross-bubble summary view? Then searches could logically dump users there.

That's a totally separate issue though. Won't close this immediately, for discussions sake, but I think this issue should be closed with, potentially, a new issue opened for the above suggestion.
