### ISSUE TITLE
Reconsider handling format check during CI

### ISSUE THREAD

**Issue by GarvinH** [TBS-EACPD/infobase#975]
We should reconsider how we handle the format check going forward.

Reasons to remove it altogether:

> To be honest, I kind of question the use of a format check step in CI. I think we don't care if some random file isn't formatted right. Rebasing, find-and-replace, code mods etc can always bypass the on-save prettier run... but it doesn't matter much since the file will reformat the next time it's opened and re-saved
> 
> All we really want to enforce is that devs actually have prettier running on-save locally, right? This is flaky for that purpose, since other changes are more likely to trigger it
> If we REALLY care, the right solution is to add a global prettier check/run as a git-hook pre-push or something (edited) 
> Easy enough to do, we've already got an example of one pre-push hook in the archive branch name convention check
> ... but might be kinda annoying, having to wait for a prettier run on every push attempt

Reasons to keep it:
> - Previously the formatter check was in individual test jobs within the CI check but they would never fail for some reason. Keeping it means the CI check would run as (previously) intended
> - Format check occurs in other projects (such as zeus)
> - New devs will know right away if prettier isn't working locally
> - Wiki says non-prettier compliant code will fail in CI (If we drop it from CI, remember to update wiki!)

Summary of current choices:
- Remove it altogether
- Keep it as is
- Use git-hooks to ensure formatting pre-push

Feel free to add suggestions

**Comment by AlexCLeduc** [comment]
If we remove format checking in CI, exceptions will end up in PRs and confuse the review process. 

If we use git hooks, I think it should just a warning you can ignore. It shouldn't automatically format everything

**Comment by ktw1016** [comment]
+1 for git hooks
