### ISSUE TITLE
infographic panel filter should clear the panel URL

### ISSUE THREAD

**Issue by AlexCLeduc** [TBS-EACPD/infobase#994]
there's a bug that can easily be reproduced:

1. visit this url that has a panel parameter: https://www.tbs-sct.gc.ca/ems-sgd/edb-bdd/index-eng.html#orgs/gov/gov/infograph/financial/.-.-(panel_key.-.-'in_year_estimates_split)
2. scroll up to the panel filter
3. select program spending, filtering occurs as expected. In particular this filters out the panel identified by the url param
4. select tabled estimates, **this will cause the page to scroll to the in-year-estimates panel**

I think we can fix this if we clear the panel key from the URL  (probably using `replaceState`, to avoid extra history entries) when a user uses the filter feature

**Comment by GarvinH** [comment]
we could possibly use react router [history.replace](https://reactrouter.com/web/api/history)
