### ISSUE TITLE
Unable to test on IE

### ISSUE THREAD

**Issue by ChetanMandur** [TBS-EACPD/infobase#998]
When trying to launch [IB locally](http://localhost:8080/build/InfoBase/index-eng.html#start) on IE, a blank template is displayed.
![image](https://user-images.githubusercontent.com/25832939/113925195-bb795600-97b8-11eb-869f-499557e1c66e.png)

This happens regardless of running `npm run serve-loopback` or ` npm run serve`

**Comment by ktw1016** [comment]
Have you tried `npm run IB_dev` ?

**Comment by ChetanMandur** [comment]
@ktw1016 that seemed to have fixed it! It wasn't listed in the wiki which is what threw me off 😅 . I'll add this, thank you!

**Comment by ktw1016** [comment]
Yes please add it into wiki!! Thanks :)
